server:
  port: 9000
spring:
  profiles:
    active: dev
  application:
    name: yyok-assembly-admin-server
  security:
    user:
      name: yyok
      password: yyok

    # 注册中心配置
#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 20
    # 设置使用IP
#    prefer-ip-address: true
    # 设置外网IP号
#    ip-address: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    instance-info-replication-interval-seconds: 30
#    registry-fetch-interval-seconds: 3
#    service-url:
#      defaultZone: http://localhost:8761/eureka





