# 数据源配置
spring:
  redis:
    database: 1
    host: 192.168.10.34
    port: 6379
    password: root   # 密码（默认为空）
    timeout: 6000ms       # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.10.34
    port: 5672
    username: admin
    password: root
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://192.168.10.34:3306/admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yyok.service.data.market.api.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# spring security 配置
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8612/auth/oauth/token
      user-authorization-uri: http://localhost:8612/auth/oauth/authorize
      client-id: yyok
      client-secret: 123456
      scope: all
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:8612/auth/oauth/check_token

# Swagger界面内容配置
swagger:
  enable: true
  title: API接口文档
  description: Api Documentation
  version: 1.0.0
  basePackage: com.yyok.service.data.market.controller
  termsOfServiceUrl: http://www.baidu.com
  contact:
    name: linqinghong
    url: http://www.baidu.com
    email: 312075478@qq.com